### ISSUE TITLE
[gitlab] - each commit is reviewed twice

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/git-eca-rest-api#20]
As reported by Antonio Garcia-Dominguez, the Gitlab ECA service is reviewing commits twice:
https://gitlab.eclipse.org/eclipsefdn/gitlab/-/issues/7#note_73

**Comment by autumnfound** [comment]
This was a one line error I made while adding warning support. Instead of iterating over the new warning messages, its hitting the standard message array again on L96. Just need to swap that to target warnings and test. I'll take a look and test later!
