### ISSUE TITLE
ECA check should (probably) not test "personal" or forked GitLab repositories

### ISSUE THREAD

**Issue by fredg02** [EclipseFdn/git-eca-rest-api#26]
It does not block pushes, but shows potentially confusing errors like "The author is not a committer on the project.".

**Comment by autumnfound** [comment]
Rebranding to enhancement, as this doesn't block contributions. I agree this could be a useful distinction and change, but this doesn't remove the need to send a request to the ECA validation service, as we don't know if the branch is associated with a project until then. The only change this would introduce is a potential flag in the output like `"tracked": false`, where we change what is written to the console.

**Comment by autumnfound** [comment]
@chrisguindon Tagging you in this, as we will need to talk to a few stakeholders in the GL server before we change how this behaves.

**Comment by chrisguindon** [comment]
> It does not block pushes, but shows potentially confusing errors like "The author is not a committer on the project.".

I agree that "on the project" is not very clear. We should update the error message to include the project name. We could also include that we know this is a fork of project X.

I am not concerned about personal projects since folks are NOT allowed to have them on Eclipse Gitlab.

**Comment by autumnfound** [comment]
Currently we don't pass a branches parent state (no parent vs fork) via the post. We'd have to change the post data to accept an additional parameter of `"forkedFrom": "someurl/name/whatever"` at the root of the JSON

**Comment by autumnfound** [comment]
This is done. We still print the output results, but if a project cannot be directly linked to a tracked Eclipse project, we don't error out. This allows pushes in other branches (and forks of good branches). The API should still trigger on merge requests and block bad pushes, so we don't lose any functionality!
