### ISSUE TITLE
When creating a new branch, a push will fail if an old commit offends the ECA check

### ISSUE THREAD

**Issue by fredg02** [EclipseFdn/git-eca-rest-api#30]
If an old commit does not pass the ECA check (anymore), how can this be fixed or circumvented?

**Comment by autumnfound** [comment]
I've created a solution that should address this issue better than the current state (#31), but there were more conversations had over the day about this. The new solution has a gap in that it relies on an up to date master branch in the fork to check new commits. This is almost never the case in my experience and would cause progressively worse validation over time.

@agafgfafa @chrisguindon and I chatted, and we've gotten to the solution to not check forks for validation, but rather warn of potential blockers in a message and not validate. This will be done in the morning (PST), and hopefully, be tested and live by early afternoon latest.

**Comment by autumnfound** [comment]
This was completed. A new check has been added that will convert errors to warnings for projects not tracked by Eclipse (i.e. forks and internal repos)
