### ISSUE TITLE
Signed-off-by validation does not support multiple authors

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/git-eca-rest-api#40]
We are currently validating the first appearance of a "Signed-off-by" but a contribution might include multiple Signed-off-by.

The order is not important in the commit message but we need to make sure that the author did include their Signed-off-by in the commit message. This is not a requirement if the author is a committer on the project.

We also need to make sure that the contributor has an ECA but we are already doing that!

**Comment by waynebeaton** [comment]
We there to be a signed-off-by for the author. Other signed-off-by entries may be present and should be ignored.
